name: crevify
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
 
  flutter:
    sdk: flutter
  
  #flutter_native_splash: ^2.3.10
  flutter_bloc: ^8.0.0 # Add flutter_bloc dependency
  equatable: ^2.0.3 # Add equatable dependency
  firebase_auth: ^4.17.4
  flutter_svg: ^2.0.10+1
  auto_size_text: 3.0.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.5
  cloud_firestore_platform_interface: ^6.1.6
  cloud_firestore_web: ^3.10.5
  collection: ^1.18.0  # updated version
  firebase_core: ^2.25.4 # updated version
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: ^2.11.4
  flutter_animate: ^4.5.0
  flutter_cache_manager: 3.3.1
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  json_path: ^0.7.0
  lottie: ^3.1.0
  page_transition: 2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.1
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: ^2.3.5
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.2.2
  smooth_page_indicator: 1.1.0
  sqflite: ^2.3.2
  stream_transform: 2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.4
  url_launcher_platform_interface: ^2.3.2

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: 3.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logos/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
