// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/widgets.dart';

import 'main.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa5O1XSh0B7aGP7iCMpM5rjP5trbO88EM',
    appId: '1:483924639801:web:2678c636649e95e87c8de8',
    messagingSenderId: '483924639801',
    projectId: 'crevify',
    authDomain: 'crevify.firebaseapp.com',
    storageBucket: 'crevify.appspot.com',
    measurementId: 'G-Q9R6J8Z5PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9DIpsDtCSJAI5IKipUFRQuYH-e1bjRo',
    appId: '1:483924639801:android:83e81937050a4b747c8de8',
    messagingSenderId: '483924639801',
    projectId: 'crevify',
    storageBucket: 'crevify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAHaZAnSIEZIgJzDM-3sWYZBTedAArto',
    appId: '1:483924639801:ios:0670960d8498eb977c8de8',
    messagingSenderId: '483924639801',
    projectId: 'crevify',
    storageBucket: 'crevify.appspot.com',
    iosBundleId: 'com.example.crevify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAHaZAnSIEZIgJzDM-3sWYZBTedAArto',
    appId: '1:483924639801:ios:bf201499dbeea4ce7c8de8',
    messagingSenderId: '483924639801',
    projectId: 'crevify',
    storageBucket: 'crevify.appspot.com',
    iosBundleId: 'com.example.crevify.RunnerTests',
  );
}
